### Health Check
GET http://localhost:8000/
Content-Type: application/json


### Signup User
POST http://localhost:8000/api/v1/signup
Content-Type: application/json

{
  "name": "Bhaskar",
  "email": "bhas@test.com",
  "password": "123456"
}


### Login User
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "email": "bhas@test.com",
  "password": "123456"
}


### Save JWT Token
# After login, copy the token from the response and paste it below
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXNrYXJAdGVzdC5jb20iLCJpZCI6IjZhOGJkMzMzM2Y2ZjgyNDI4YzkwY2E2YSIsIm5hbWUiOiJCaGFza2FyIiwiaWF0IjoxNzg3NTQ4NTA4LCJleHAiOjE3ODgxNTMzMDh9.n09aTA33EhY1cFWtWHtQiIP4j6xPamJx7bdruK9JSKg


### Get Logged-in User Profile
GET http://localhost:8000/api/v1/me
Authorization: Bearer {{token}}
Content-Type: application/json


### Checkout (Protected Route)
POST http://localhost:8000/api/v1/checkout
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "name": "Yard Special",
      "price": 15,
      "quantity": 1
    }
  ],
  "total": 15,
  "deliveryAddress": {
    "street": "123 Main St",
    "city": "Sydney",
    "state": "NSW",
    "postcode": "2000"
  }
}
